version: "3"

services:
  backend:
    image: paskot.com/backend-service
    ports:
      - "9000:9000"
      - "9001:9001"
  frontend:
    image: nginx:stable
    ports:
      - "8080:8080"
    links:
      - backend
    volumes:
      - ../frontend/dist:/var/www:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  postgres:
    image: postgres:9.6.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demo_banking
    volumes:
      - ./data:/var/lib/postgresql/data
